name = "Hadleyverse"
uuid = "d4083892-cce6-48ab-a9ff-eaff78e11314"
authors = ["Dai ZJ <zhuojia.dai@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
DataFrames = "0.21"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
